[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "gspread>=6.2.1",
    "oauth2client>=4.1.3",
    "pillow>=12.1.0",
    "python-telegram-bot>=22.6",
    "qrcode>=8.2",
    "telegram>=0.0.1",
]
